//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingRooms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public int EmployeeId { get; set; }
        public int RoomId { get; set; }
        public string Description { get; set; }
        public System.DateTime BookedFrom { get; set; }
        public System.DateTime BookedTo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
    }
}
